services:
  kafka:
    image: ashish1981/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_CREATE_TOPICS=topic-a,topic-b,topic-c
      - KRAFT_PARTITIONS_PER_TOPIC=3
      - KRAFT_AUTO_CREATE_TOPICS=true
    volumes:
      - ./data:/opt/kafka/data
      - ./logs:/opt/kafka/logs
      - ./config:/opt/kafka/config/kraft
