name: CI

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short=12 HEAD)"

      - name: Build and push latest
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: moeenz/docker-kafka-kraft:${{steps.vars.outputs.sha_short}},moeenz/docker-kafka-kraft:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
